import React, { useState, useEffect } from 'react';
import { DownloadPack, DownloadLink } from '../types/movie';
import { 
  X, Check, Download, ShieldCheck, Copy, 
  ExternalLink, HardDrive, RefreshCw, CheckCircle2 
} from 'lucide-react';

interface DownloadModalProps {
  pack: DownloadPack | null;
  link: DownloadLink | null;
  movieTitle: string;
  onClose: () => void;
}

export const DownloadModal: React.FC<DownloadModalProps> = ({
  pack,
  link,
  movieTitle,
  onClose
}) => {
  const [countdown, setCountdown] = useState<number>(3);
  const [isReady, setIsReady] = useState<boolean>(false);
  const [copiedMagnet, setCopiedMagnet] = useState<boolean>(false);
  const [downloadTriggered, setDownloadTriggered] = useState<boolean>(false);

  useEffect(() => {
    if (!pack || !link) return;
    setCountdown(3);
    setIsReady(false);
    setDownloadTriggered(false);

    const timer = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          setIsReady(true);
          return 0;
        }
        return prev - 1;
      });
    }, 900);

    return () => clearInterval(timer);
  }, [pack, link]);

  if (!pack || !link) return null;

  const simulatedMagnet = `magnet:?xt=urn:btih:${movieTitle.toLowerCase().replace(/[^a-z0-9]/g, '')}_${pack.tier.replace(/[^a-z0-9]/gi, '_')}&dn=${encodeURIComponent(movieTitle)}&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce`;

  const handleCopyMagnet = () => {
    navigator.clipboard.writeText(simulatedMagnet);
    setCopiedMagnet(true);
    setTimeout(() => setCopiedMagnet(false), 2500);
  };

  const handleStartDownload = () => {
    setDownloadTriggered(true);
    // Create a dummy download file simulation
    const blob = new Blob([
      `MovieHub4y High Speed Download Verification\n\nMovie: ${movieTitle}\nQuality: ${pack.tier}\nSize: ${pack.size}\nServer: ${link.serverName}\nCodec: ${pack.codec}\nAudio: ${pack.audioSpec}\n\nGenerated by moviehub4y.online Official Portal\nThank you for choosing MovieHub4y!`
    ], { type: 'text/plain' });
    
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${movieTitle.replace(/[^a-zA-Z0-9_-]/g, '_')}_${pack.tier.replace(/\s+/g, '_')}_MovieHub4y.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-60 bg-black/85 backdrop-blur-md flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div 
        className="relative w-full max-w-lg bg-[#0e111a] border border-slate-800 rounded-2xl shadow-2xl overflow-hidden text-slate-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 bg-slate-900 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <HardDrive className="w-4 h-4 text-amber-400" />
            <span className="text-xs font-bold text-white font-mono uppercase tracking-wider">
              MovieHub4y Fast Cloud Link Generator
            </span>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-md hover:bg-slate-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 sm:p-6 space-y-5">
          {/* File Card info */}
          <div className="p-3.5 bg-slate-900/80 rounded-xl border border-slate-800 space-y-1.5">
            <span className="text-[10px] text-amber-400 font-mono uppercase font-bold tracking-wider">
              File Target
            </span>
            <h4 className="text-sm font-bold text-white leading-snug">
              {movieTitle}
            </h4>
            <div className="flex flex-wrap items-center gap-2 pt-1 text-xs text-slate-400 font-mono">
              <span className="bg-amber-500/20 text-amber-300 px-2 py-0.5 rounded font-semibold text-[11px]">
                {pack.tier}
              </span>
              <span>·</span>
              <span className="text-emerald-400 font-bold">{pack.size}</span>
              <span>·</span>
              <span className="text-slate-300">{link.serverName}</span>
            </div>
          </div>

          {/* Verification / Generation State */}
          {!isReady ? (
            <div className="py-6 flex flex-col items-center justify-center space-y-3 text-center">
              <div className="relative">
                <RefreshCw className="w-10 h-10 text-amber-400 animate-spin" />
                <span className="absolute inset-0 flex items-center justify-center text-xs font-bold font-mono text-amber-200">
                  {countdown}
                </span>
              </div>
              <div>
                <p className="text-sm font-semibold text-white">
                  Connecting to {link.serverName}...
                </p>
                <p className="text-xs text-slate-400">
                  Checking server bandwidth & bypass verification ({countdown}s)
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-4 animate-in fade-in zoom-in-95 duration-200">
              <div className="p-3 bg-emerald-950/40 border border-emerald-500/30 rounded-lg flex items-center gap-2.5 text-xs text-emerald-300">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <div>
                  <span className="font-bold">Direct Link Generated Successfully!</span>
                  <p className="text-[11px] text-emerald-400/80">No waiting time. High-speed multi-threaded download enabled.</p>
                </div>
              </div>

              {/* Primary Action Button */}
              <button
                onClick={handleStartDownload}
                className="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-slate-950 font-black text-sm flex items-center justify-center gap-2 shadow-xl shadow-amber-500/20 transition-all hover:scale-[1.01] active:scale-[0.99]"
              >
                <Download className="w-4 h-4 stroke-[2.5]" />
                <span>{downloadTriggered ? 'Download Again' : 'Click Here To Download'}</span>
              </button>

              {downloadTriggered && (
                <p className="text-[11px] text-center text-emerald-400 font-medium">
                  ✓ Download triggered! Check your browser's download manager.
                </p>
              )}

              {/* Secondary Options */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                <button
                  onClick={handleCopyMagnet}
                  className="py-2.5 px-3 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 border border-slate-700 transition-colors"
                >
                  {copiedMagnet ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                      <span className="text-emerald-300">Magnet Link Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-amber-400" />
                      <span>Copy Magnet / Torrent</span>
                    </>
                  )}
                </button>

                <a
                  href={link.url}
                  target="_blank"
                  rel="noreferrer"
                  className="py-2.5 px-3 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 border border-slate-700 transition-colors text-center"
                >
                  <ExternalLink className="w-3.5 h-3.5 text-sky-400" />
                  <span>Open Cloud Mirror</span>
                </a>
              </div>

              {/* Security & Playback Tips */}
              <div className="pt-2 border-t border-slate-800/80 space-y-1.5 text-[11px] text-slate-400">
                <div className="flex items-center gap-1.5 text-slate-300 font-semibold">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Tips for Smooth Playback</span>
                </div>
                <ul className="list-disc list-inside space-y-1 text-slate-400 leading-relaxed">
                  <li>Use <strong className="text-slate-300">VLC Media Player</strong> or <strong className="text-slate-300">MX Player</strong> to toggle between Hindi and Dual Audio tracks.</li>
                  <li>Files are packed in MKV/MP4 container with 100% clean verified checksums.</li>
                </ul>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
